### ISSUE TITLE
Orders not appear on my account 

### ISSUE THREAD

**Issue by Able2Code** [DivanteLtd/vue-storefront#1794]
![ordini](https://user-images.githubusercontent.com/5517831/46247322-efb27580-c409-11e8-9ab2-27d11b910018.gif)

**Comment by pkarw** [comment]
Have you “npm run o2m” up and running? Orders are displayed only after they’re transferred to backend (Magento in that case). Otherwise the list is empty

**Comment by Able2Code** [comment]
I see this problem in 
https://demo.vuestorefront.io/my-account/orders

**Comment by pkarw** [comment]
Fixed - the order_2_magento.js process encountered some problems on demo host 
Now it's fine:
https://www.dropbox.com/s/aj2pxggnro7ttlg/Screenshot%202018-09-29%2022.15.04.png?dl=0

**Comment by Ananth747** [comment]
@pkarw Order cannot be placed on demo host: https://demo.vuestorefront.io/
**Request URL:** https://demo.vuestorefront.io/api/order
**Response:**
```
{code: 500, result: {command: "INCR", args: ["q:ids"], code: "MISCONF"}}
code: 500
result: {command: "INCR", args: ["q:ids"], code: "MISCONF"}
args: ["q:ids"]
code: "MISCONF"
command: "INCR"
```

**Comment by pkarw** [comment]
This was a Redis issue, already fixed on the test env.

**Comment by Nolaan** [comment]
Still not working, the orders are not showing up on my account eventhough there's a confirmation from the server.
Furthermore the account details cannot be updated.

**Comment by pkarw** [comment]
And after refreshing the whole page (Ctrl+F5) the order is there? it should
